### ISSUE TITLE
Generate a token from IAM User credentials using the GetFederationToken API

### ISSUE THREAD

**Issue by nathandines** [vibrato/awskeyring#17]
**Use case:** Short-lived credentials on the CLI to prevent leaving valid credentials in long-lived sessions

I'm thinking this might be able to be implemented to leverage the `token` subcommand

**Comment by nathandines** [comment]
Also worth noting to cater for the 32 character limit on the session names :)

**Comment by tristanmorgan** [comment]
implemented.
